### ISSUE TITLE
Checklist for stable release launch

### ISSUE THREAD

**Issue by FlashyReese** [FlashyReese/decky-wine-cellar#1]
## Todo List
- [x] Proton Flavours
    - [x] Proton GE
    - [x] Luxtorpeda
    - [x] Boxtron
- [x] Asynchronous queue downloader
- [x] Revamp frontend
    - [x] Add dashboard to manage all installed compatibility tools
    - [x] Add settings page
        - [x] Check for updates ~~(we need to notify the user on only 60 requests per hour github api calls)~~
    - [x] Markdown renderer for compatibility tools changelog
    - [x] Use a progress bar for progress indication
    - [x] Detect which Steam games are using the compatibility tool using `vdf` files
    - [x] Add functionality to manage the download queue (cancel, ~~move up, move down~~)
    - [x] Implement a prompt asking the user to restart after the compatibility tool is done installing.
